### ISSUE TITLE
about your pre-train model

### ISSUE THREAD

**Issue by 37integer** [SerezD/NVAE-from-scratch#2]
i download your pretrain checkpoint, it seems have problem in your celeb10 checkpoint, i can't use it.
```
Traceback (most recent call last):
  File "/miniconda3/envs/nvae_from_scratch/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 76, in _wrap
    fn(i, *args)
  File "/workshop/NVAE-from-scratch/src/scripts/update_bn_stats.py", line 47, in update_bn
    checkpoint = torch.load(args.checkpoint_path, map_location='cpu')
  File "/miniconda3/envs/nvae_from_scratch/lib/python3.10/site-packages/torch/serialization.py", line 1072, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/miniconda3/envs/nvae_from_scratch/lib/python3.10/site-packages/torch/serialization.py", line 480, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by SerezD** [comment]
Hi, I do not know what causes the issue. However, I have re-loaded a new version of the model at: https://huggingface.co/SerezD/NVAE-from-scratch/tree/main/celeba64

I have tried to download, unzip, and load it and it works for me. Let me know if this solves the issue for you too.

**Comment by 37integer** [comment]
the new version worked now, thank you

**Comment by 37integer** [comment]
solved
